INSIGHT-967: add rest api guards
nuxeo/nuxeo-ai pull request #406
Opened 2021-04-15 21:27 UTC by vpasquier

2021-04-15 21:27 UTC, nuxeojenkins commented
View issue in JIRA: [INSIGHT-967](https://jira.nuxeo.com/browse/INSIGHT-967)

2021-04-15 21:27 UTC, vpasquier commented
@jcarsique i need a review on the pom of the internal - lets see that in a meeting

2021-04-16 12:37 UTC, jcarsique requested changes

2021-04-16 12:37 UTC, jcarsique commented on pom.xml
> +    <version>10.10-HF44</version>
Upgrade this version only if needed for compile or runtime: the version stated here is used as a minimal requirement for the Marketplace packages.

2021-04-16 12:37 UTC, jcarsique commented on pom.xml
> +        <version>10.10</version>
<version>${nuxeo.platform.version}</version>

2021-04-16 12:37 UTC, jcarsique commented on pom.xml
> +        <version>10.10</version>
<version>${nuxeo.platform.version}</version>

2021-04-16 12:37 UTC, jcarsique commented on pom.xml
> +        <version>10.10</version>
<version>${nuxeo.platform.version}</version>

2021-04-16 12:37 UTC, jcarsique commented on pom.xml
> +    <module>nuxeo-ai-internal</module>
This module no more needs a special treatment, remove the dedicated lines in tools/release.sh and tools/sprint.sh
https://github.com/nuxeo/nuxeo-ai/blob/766ddbd25b9f13f58c0c7ba931eea6440218b1f7/tools/release.sh#L43
https://github.com/nuxeo/nuxeo-ai/blob/766ddbd25b9f13f58c0c7ba931eea6440218b1f7/tools/release.sh#L58
https://github.com/nuxeo/nuxeo-ai/blob/766ddbd25b9f13f58c0c7ba931eea6440218b1f7/tools/sprint.sh#L128

2021-04-19 08:05 UTC, andreinechaev approved these changes

2021-04-19 15:56 UTC, merged